name: Release DBI Patcher

on:
  push:
    tags:
      - 'v*' 

permissions:
  contents: write 

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "Windows Build"
            os: windows-latest
            artifact_name: dbipatcher-windows
            binary_name: dbipatcher.exe
            
          - name: "Linux Build"
            os: ubuntu-latest
            artifact_name: dbipatcher-linux
            binary_name: dbipatcher
            
          - name: "macOS Build"
            os: macos-latest
            artifact_name: dbipatcher-macos
            binary_name: dbipatcher

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up build environment
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update
          sudo apt-get install -y build-essential
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew update
          brew install make gcc
        fi
        # Windows

    - name: Build the project
      run: |
        make clean
        make -j4
        if [ -f "bin/dbipatcher" ]; then
          mkdir -p release/
          cp bin/dbipatcher release/dbipatcher-${{ runner.os }}
        fi
        if [ -f "bin/dbipatcher.exe" ]; then
          mkdir -p release/
          cp bin/dbipatcher.exe release/dbipatcher-windows.exe
        fi

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: |
          release/
          bin/
        if-no-files-found: error

  create-release:
    runs-on: ubuntu-latest
    needs: build-and-release
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all build artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          DBI Patcher ${{ github.ref_name }}
          
          Automated build containing binaries for:
          - Windows (x86_64)
          - Linux (x86_64) 
          - macOS (x86_64)
          
          **How to use:**
          1. Download the appropriate binary for your platform
          2. Make it executable (on Linux/macOS): `chmod +x dbipatcher`
          3. Run with: `./dbipatcher [options]`
        draft: false
        prerelease: false

    - name: Upload Windows binary
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/dbipatcher-windows/dbipatcher-windows.exe
        tag_name: ${{ github.ref_name }}

    - name: Upload Linux binary
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/dbipatcher-linux/dbipatcher
        tag_name: ${{ github.ref_name }}

    - name: Upload macOS binary
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/dbipatcher-macos/dbipatcher
        tag_name: ${{ github.ref_name }}

    - name: Upload additional files
      uses: softprops/action-gh-release@v1
      with:
        files: |
          README.md
          LICENSE
          translate/rec6.810.*.txt
        tag_name: ${{ github.ref_name }}
