name: Release DBI Patcher

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install MinGW and verify tools
      run: |
        choco install mingw -y
        echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $env:GITHUB_PATH
        gcc --version
        make --version
        
    - name: Verify source files and directory structure
      run: |
        Write-Host "Checking source directory structure:"
        Get-ChildItem -Path . -Recurse -Directory | Where-Object { $_.Name -eq "src" } | ForEach-Object { 
            Write-Host "Found src directory at: $($_.FullName)"
            Get-ChildItem -Path $_.FullName -Recurse -File
        }
        
        if (Test-Path "src\*.c") {
            Write-Host "C source files found in src/:"
            Get-ChildItem -Path "src" -Filter "*.c"
        } else {
            Write-Host "No C source files found in src/"
        }
        
        if (Test-Path "src\inc\*.h") {
            Write-Host "Header files found in src/inc/:"
            Get-ChildItem -Path "src\inc" -Filter "*.h"
        } else {
            Write-Host "No header files found in src/inc/"
        }

    - name: Verify pre-built zstd DLL
      run: |
        if (Test-Path "libs/zstd/dll/libzstd.dll") { 
            Write-Host "Pre-built libzstd.dll found" 
            Get-Item "libs/zstd/dll/libzstd.dll"
        } else { 
            Write-Host "Error: Pre-built libzstd.dll not found" 
            Write-Host "Available files in libs/zstd/dll/:"
            if (Test-Path "libs/zstd/dll") {
                Get-ChildItem -Path "libs/zstd/dll"
            }
            exit 1 
        }

    - name: Build for Windows
      run: |
        make clean
        make -j4

    - name: Verify build output
      run: |
        if (Test-Path "bin/dbipatcher.exe") { 
            Write-Host "Build successful: dbipatcher.exe found" 
            Get-Item "bin/dbipatcher.exe"
            if (Test-Path "bin/libzstd.dll") { 
                Write-Host "libzstd.dll copied to bin directory" 
            }
        } else { 
            Write-Host "Build failed: dbipatcher.exe not found" 
            if (Test-Path "build") {
                Write-Host "Build directory contents:"
                Get-ChildItem -Path "build" -Recurse
            }
            exit 1 
        }

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: dbipatcher-windows
        path: |
          bin/dbipatcher.exe
          bin/libzstd.dll
        if-no-files-found: error

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential make libzstd-dev

    - name: Build for Linux
      run: |
        make clean
        make -j4

    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: dbipatcher-linux
        path: bin/dbipatcher
        if-no-files-found: error

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        brew update
        brew install make zstd
        echo "PATH=/opt/homebrew/bin:/usr/local/bin:$PATH" >> $GITHUB_ENV

    - name: Build for macOS
      run: |
        make clean
        make -j4

    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: dbipatcher-macos
        path: bin/dbipatcher
        if-no-files-found: error

  create-release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux, build-macos]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: List downloaded files
      run: |
        find artifacts -type f | sort

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: DBI Patcher ${{ github.ref_name }}
        body: |
          Automated build of DBI Patcher ${{ github.ref_name }}

          **Platforms included:**
          - Windows (x86_64)
          - Linux (x86_64)
          - macOS (x86_64)

          **Usage:**
          ```bash
          # Linux/macOS
          chmod +x dbipatcher
          ./dbipatcher --help

          # Windows
          dbipatcher.exe --help
          ```
        draft: false
        prerelease: false
        files: |
          artifacts/dbipatcher-windows/dbipatcher.exe
          artifacts/dbipatcher-linux/dbipatcher
          artifacts/dbipatcher-macos/dbipatcher
